version: "3.8"

services:
  drupal:
    image: drupal:7.94-apache
    container_name: drupal7
    ports:
      - "8081:80"
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
    volumes:
      - ./drupal:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: drupal7-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
