name: Build and Deploy Drupal 7

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/drupal7:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/drupal7:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy.key
          chmod 600 deploy.key

      - name: Deploy to server
        run: |
          ssh -i deploy.key -o StrictHostKeyChecking=no root@YOUR_SERVER_IP \
          "docker pull ${{ secrets.DOCKER_USERNAME }}/drupal7:latest && \
           docker stop drupal7 || true && \
           docker rm drupal7 || true && \
           docker run -d --name drupal7 -p 80:80 \
           --link drupal7-db:db \
           ${{ secrets.DOCKER_USERNAME }}/drupal7:latest"
